const elements = {
  A: { name: "Ambitium", meaning: "Ambition" },
  B: { name: "Bravium", meaning: "Bravery" },
  C: { name: "Cryptium", meaning: "Mystery" },
  D: { name: "Dominium", meaning: "Dominance" },
  E: { name: "Enigmium", meaning: "Enigma" },
  F: { name: "Fortium", meaning: "Strength" },
  G: { name: "Genium", meaning: "Genius" },
  H: { name: "Honorium", meaning: "Honor" },
  I: { name: "Intellectium", meaning: "Intellect" },
  J: { name: "Justium", meaning: "Justice" },
  K: { name: "Kinetium", meaning: "Motion" },
  L: { name: "Luminarium", meaning: "Illumination" },
  M: { name: "Mentisium", meaning: "Mind" },
  N: { name: "Noctum", meaning: "Night/Mystery" },
  O: { name: "Omnium", meaning: "Everything" },
  P: { name: "Potentium", meaning: "Power" },
  Q: { name: "Quietium", meaning: "Silence" },
  R: { name: "Rationium", meaning: "Reason" },
  S: { name: "Strategium", meaning: "Strategy" },
  T: { name: "Triumphium", meaning: "Triumph" },
  U: { name: "Ultimium", meaning: "Ultimate" },
  V: { name: "Veritium", meaning: "Truth" },
  W: { name: "Wisdium", meaning: "Wisdom" },
  X: { name: "Xanadium", meaning: "Utopia" },
  Y: { name: "Yernium", meaning: "Yearning" },
  Z: { name: "Zenithium", meaning: "Peak" },
};
